---
repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.7.4
    hooks:
      - id: pylint
        args:
          - "--disable=C0103,E0401,R0801"
          - "--max-line-length=128"
        files: pysequila,*.py
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - "--line-length=128"
        files: pysequila,*.py
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        args: ["-l 128"]
        files: pysequila/*.py,*.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-added-large-files
